### ISSUE TITLE
Problems reading some CMIP6 XMLs (or the netCDF files they point to)

### ISSUE THREAD

**Issue by covey1** [pochedls/xagg#10]
The good news is that I can read Paul and Steve's XMLs for 16 of the 18 institutions contributing to CMIP6. The bad news--involving the other two institutions, BCC and CAMS--is that the same script gets error messages detailed in the attached MS Word document.
[processedCMIP6Models26Sep2019.docx](https://github.com/pochedls/xagg/files/3659988/processedCMIP6Models26Sep2019.docx)

**Comment by durack1** [comment]
Contents of the word docx:
```
Geopotential from 16 CMIP6 models has been processed by getCMIP6MonthlyClim.py on grim.llnl.gov directory /export_backup/covey1/StationaryWaveDiagnostics to give January- and July-mean climatology:
(jupyter-vcdat) -bash-4.1$ ls -l *.1990-1-1to2013-12-31.J*s.nc
-rw-r----- 1 covey1 climate  5835102 Sep 25 13:37 AWI-CM-1-1-MR.1990-1-1to2013-12-31.JANs.nc
-rw-r----- 1 covey1 climate  5739022 Sep 25 16:51 AWI-CM-1-1-MR.1990-1-1to2013-12-31.JULs.nc
-rw-r----- 1 covey1 climate   709334 Sep 25 16:57 CanESM5.1990-1-1to2013-12-31.JANs.nc
-rw-r----- 1 covey1 climate   700784 Sep 25 17:13 CanESM5.1990-1-1to2013-12-31.JULs.nc
-rw-r----- 1 covey1 climate  4265300 Sep 25 17:10 CESM2.1990-1-1to2013-12-31.JANs.nc
-rw-r----- 1 covey1 climate  4166574 Sep 25 17:24 CESM2.1990-1-1to2013-12-31.JULs.nc
-rw-r----- 1 covey1 climate  2419014 Sep 25 16:58 CNRM-CM6-1.1990-1-1to2013-12-31.JANs.nc
-rw-r----- 1 covey1 climate  2390720 Sep 25 17:13 CNRM-CM6-1.1990-1-1to2013-12-31.JULs.nc
-rw-r----- 1 covey1 climate  4914444 Sep 25 17:01 E3SM-1-0.1990-1-1to2013-12-31.JANs.nc
-rw-r----- 1 covey1 climate  4843889 Sep 25 17:16 E3SM-1-0.1990-1-1to2013-12-31.JULs.nc
-rw-r----- 1 covey1 climate 10971729 Sep 25 17:07 EC-Earth3.1990-1-1to2013-12-31.JANs.nc
-rw-r----- 1 covey1 climate 10702746 Sep 25 17:20 EC-Earth3.1990-1-1to2013-12-31.JULs.nc
-rw-r----- 1 covey1 climate  3825569 Sep 25 17:36 GFDL-CM4.1990-1-1to2013-12-31.JANs.nc
-rw-r----- 1 covey1 climate  3753692 Sep 25 17:24 GFDL-CM4.1990-1-1to2013-12-31.JULs.nc
-rw-r----- 1 covey1 climate  1048976 Sep 25 17:10 GISS-E2-1-G.1990-1-1to2013-12-31.JANs.nc
-rw-r----- 1 covey1 climate  1034133 Sep 25 17:23 GISS-E2-1-G.1990-1-1to2013-12-31.JULs.nc
-rw-r----- 1 covey1 climate  2076460 Sep 25 17:09 HadGEM3-GC31-LL.1990-1-1to2013-12-31.JANs.nc
-rw-r----- 1 covey1 climate  2035402 Sep 25 17:22 HadGEM3-GC31-LL.1990-1-1to2013-12-31.JULs.nc
-rw-r----- 1 covey1 climate  1651912 Sep 25 17:08 IPSL-CM6A-LR.1990-1-1to2013-12-31.JANs.nc
-rw-r----- 1 covey1 climate  1611516 Sep 25 17:21 IPSL-CM6A-LR.1990-1-1to2013-12-31.JULs.nc
-rw-r----- 1 covey1 climate   773234 Sep 25 17:37 MCM-UA-1-0.1990-1-1to2013-12-31.JANs.nc
-rw-r----- 1 covey1 climate   705894 Sep 25 17:26 MCM-UA-1-0.1990-1-1to2013-12-31.JULs.nc
-rw-r----- 1 covey1 climate  2553809 Sep 25 17:09 MIROC6.1990-1-1to2013-12-31.JANs.nc
-rw-r----- 1 covey1 climate  2491287 Sep 25 17:22 MIROC6.1990-1-1to2013-12-31.JULs.nc
-rw-r----- 1 covey1 climate  3937897 Sep 25 17:10 MRI-ESM2-0.1990-1-1to2013-12-31.JANs.nc
-rw-r----- 1 covey1 climate  3854368 Sep 25 17:23 MRI-ESM2-0.1990-1-1to2013-12-31.JULs.nc
-rw-r----- 1 covey1 climate  1526141 Sep 25 17:36 NESM3.1990-1-1to2013-12-31.JANs.nc
-rw-r----- 1 covey1 climate  1514677 Sep 25 17:25 NESM3.1990-1-1to2013-12-31.JULs.nc
-rw-r--r-- 1 covey1 climate  3825569 Aug  4 15:07 NOAA-GFDL.GFDL-CM4.1990-1-1to2013-12-31.JANs.nc
-rw-r--r-- 1 covey1 climate  3753692 Jul  9 12:49 NOAA-GFDL.GFDL-CM4.1990-1-1to2013-12-31.JULs.nc
-rw-r----- 1 covey1 climate  4241822 Sep 25 17:36 SAM0-UNICON.1990-1-1to2013-12-31.JANs.nc
-rw-r----- 1 covey1 climate  4142643 Sep 25 17:26 SAM0-UNICON.1990-1-1to2013-12-31.JULs.nc

...but two other models — BCC-CSM2-MR and CAMS-CSM1-0 — have XMLs that “don’t compute.” For details, see transcript on the following page.
 
Note same error message from both of the problematic XML files. Of course, the problem may lie with the original netCDF files that the XMLs point to:

(jupyter-vcdat) -bash-4.1$ pwd
/export_backup/covey1/StationaryWaveDiagnostics

(jupyter-vcdat) -bash-4.1$ python getCMIP6MonthlyClim.py 
Reading time interval ('1990-1-1', '2013-12-31') from /p/user_pub/xclim/CMIP6/CMIP/historical/atmos/mon/zg/CMIP6.CMIP.historical.BCC.BCC-CSM2-MR.r1i1p1f1.mon.zg.atmos.glb-p19-gn.v20181126.0000000.0.xml ...

Traceback (most recent call last):
  File "getCMIP6MonthlyClim.py", line 39, in <module>
    clim = cdutil.JAN.climatology(x) # <------------------------------------------------------ Select month here...
  File "/usr/local/anaconda2/envs/jupyter-vcdat/lib/python3.7/site-packages/cdutil-8.1-py3.7.egg/cdutil/times.py", line 1583, in climatology
  File "/usr/local/anaconda2/envs/jupyter-vcdat/lib/python3.7/site-packages/cdutil-8.1-py3.7.egg/cdutil/times.py", line 478, in get
  File "/usr/local/anaconda2/envs/jupyter-vcdat/lib/python3.7/site-packages/cdutil-8.1-py3.7.egg/cdutil/times.py", line 752, in monthBasedSlicer
TypeError: 'NoneType' object is not subscriptable

(jupyter-vcdat) -bash-4.1$ python getCMIP6MonthlyClim.py 
Reading time interval ('1990-1-1', '2013-12-31') from /p/user_pub/xclim/CMIP6/CMIP/historical/atmos/mon/zg/CMIP6.CMIP.historical.CAMS.CAMS-CSM1-0.r1i1p1f1.mon.zg.atmos.glb-p19-gn.v20190708.0000000.0.xml ...

Traceback (most recent call last):
  File "getCMIP6MonthlyClim.py", line 39, in <module>
    clim = cdutil.JAN.climatology(x) # <------------------------------------------------------ Select month here...
  File "/usr/local/anaconda2/envs/jupyter-vcdat/lib/python3.7/site-packages/cdutil-8.1-py3.7.egg/cdutil/times.py", line 1583, in climatology
  File "/usr/local/anaconda2/envs/jupyter-vcdat/lib/python3.7/site-packages/cdutil-8.1-py3.7.egg/cdutil/times.py", line 478, in get
  File "/usr/local/anaconda2/envs/jupyter-vcdat/lib/python3.7/site-packages/cdutil-8.1-py3.7.egg/cdutil/times.py", line 752, in monthBasedSlicer
TypeError: 'NoneType' object is not subscriptable
(jupyter-vcdat) -bash-4.1$
```

**Comment by pochedls** [comment]
I can reproduce this issue using one of the xml files @covey1 references: 
```
fn = '/p/user_pub/xclim/CMIP6/CMIP/historical/atmos/mon/zg/CMIP6.CMIP.historical.BCC.BCC-CSM2-MR.r1i1p1f1.mon.zg.atmos.glb-p19-gn.v20181126.0000000.0.xml'
f = cdms2.open(fn)
zg = f('zg')
djfclim = cdutil.DJF.climatology(zg)
```
> ---------------------------------------------------------------------------
> TypeError                                 Traceback (most recent call last)
> <ipython-input-13-7ce657d9b8a2> in <module>()
> ----> 1 djfclim = cdutil.DJF.climatology(zg)
> 
> ~/bin/anaconda2/envs/cdat8/lib/python3.6/site-packages/cdutil/times.py in climatology(self, slab, criteriaarg, criteriaargclim, statusbar, sum)
>    1581                 statusbar=statusbar,
>    1582                 weights=True,
> -> 1583                 sum=sum)
>    1584             if tmp is None:
>    1585                 return None
> 
> ~/bin/anaconda2/envs/cdat8/lib/python3.6/site-packages/cdutil/times.py in get(self, slab, slicerarg, criteriaarg, statusbar, weights, sum)
>     476         tim = slab.getTime()
>     477         # Let slicer figure out wich slices we want
> --> 478         slices, bounds, norm = self.slicer(tim, slicerarg)
>     479 # print 'Slices:',slices,len(slices)
>     480 # print 'Bounds:',bounds
> 
> ~/bin/anaconda2/envs/cdat8/lib/python3.6/site-packages/cdutil/times.py in monthBasedSlicer(tim, arg)
>     750     nt = len(tim)
>     751     for i in range(nt):
> --> 752         b0 = cdtime.reltime(bnds[i][0], units)
>     753         b1 = cdtime.reltime(bnds[i][1], units)
>     754         iout = 0
> 
> TypeError: 'NoneType' object is not subscriptable

But I don't have this problem with the underlying netCDF files:
```
fn = '/p/css03/esgf_publish/CMIP6/CMIP/BCC/BCC-CSM2-MR/historical/r1i1p1f1/Amon/zg/gn/v20181126/zg_Amon_BCC-CSM2-MR_historical_r1i1p1f1_gn_185001-188912.nc'
f = cdms2.open(fn)
zg = f('zg')
djfclim = cdutil.DJF.climatology(zg)
```

**Comment by durack1** [comment]
@pochedls probably an issue with the time axis that the xml resolves

**Comment by pochedls** [comment]
I'm not sure if this is a cdutil / cdms issue or a cdscan issue. Maybe @durack1 has seen this before?

**Comment by lee1043** [comment]
Having `cdutil.setTimeBoundsMonthly(zg)` above of `djfclim = cdutil.DJF.climatology(zg)` will resolve the issue.

**Comment by lee1043** [comment]
```python
>>> import cdms2
>>> import cdutil
>>> f = cdms2.open(fn)
>>> zg = f('zg')
>>> djfclim = cdutil.DJF.climatology(zg)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/export_backup/lee1043/anaconda2/envs/pmp_nightly_20190617/lib/python3.7/site-packages/cdutil-8.1-py3.7.egg/cdutil/times.py", line 1583, in climatology
  File "/export_backup/lee1043/anaconda2/envs/pmp_nightly_20190617/lib/python3.7/site-packages/cdutil-8.1-py3.7.egg/cdutil/times.py", line 478, in get
  File "/export_backup/lee1043/anaconda2/envs/pmp_nightly_20190617/lib/python3.7/site-packages/cdutil-8.1-py3.7.egg/cdutil/times.py", line 752, in monthBasedSlicer
TypeError: 'NoneType' object is not subscriptable
>>> cdutil.setTimeBoundsMonthly(zg)
>>> djfclim = cdutil.DJF.climatology(zg)
>>> djfclim.shape
(1, 19, 160, 320)
```

**Comment by pochedls** [comment]
Thanks @lee1043. @covey1 - I'm closing this one out as it appears this will resolve the issue.

**Comment by durack1** [comment]
Thanks @lee1043, I would be a little careful with the use of `setTimeBoundsMonthly`, you'd probably want to run some sanity checks to ensure that it's solving the issue the right way - but @pochedls has already closed this, so..

**Comment by lee1043** [comment]
@durack1 I agree with you, some sanity checks always needed ti make sure are you are dealing with "actual" monthly data.

**Comment by pochedls** [comment]
@durack1 - reopen if you think this should be resolved by xagg in some way (but if you do, I think it makes sense to open a ticket with cdms and link it to this issue).

**Comment by durack1** [comment]
@pochedls I believe there is a `cdscan2` file lurking around somewhere, and...

**Comment by pochedls** [comment]
@durack1 - I don't think cdscan2 would fix this issue.

**Comment by durack1** [comment]
@pochedls course it would, by it's very name it's v2, clearly better than the non-versioned (v1)
