### ISSUE TITLE
specifying correct naming of netcdf files in search

### ISSUE THREAD

**Issue by mzelinka** [pochedls/xagg#16]
Some of the files published by NCC are in the format 
variable_Amon_experiment_modelname_etc and some are variable_Amon_modelname_experiment_etc. The latter is the recommended format.

In response to this issue, I am wondering if it would be a good idea for cdscan to specifically search for filenames written correctly, i.e., specifying
 
filename = '+var+'_Amon_'+model+'_'+exp+'_'+ripf+'_gn_*.nc'
 
in the search.

**Comment by pochedls** [comment]
One example where this is an issue is in the following directory: 

> /p/css03/scratch/cmip6/CMIP/NCC/NorESM2-LM/abrupt-4xCO2/r1i1p1f1/Amon/rsut/gn/v20190815/

There are misnamed files in this path (which overlap in time with the correctly named files). This results in a cdscan error:

> /p/css03/scratch/cmip6/CMIP/NCC/NorESM2-LM/abrupt-4xCO2/r1i1p1f1/Amon/rsut/gn/v20190815/rsut_Amon_NorESM2-LM_abrupt-4xCO2_r1i1p1f1_gn_029101-030012.nc
> Setting reference time units to days since 0001-01-01 00:00:00
> Traceback (most recent call last):
>   File "/export_backup/pochedley1/bin/anaconda2/envs/cdat81/bin/cdscan", line 1840, in <module>
>     main(sys.argv)
>   File "/export_backup/pochedley1/bin/anaconda2/envs/cdat81/bin/cdscan", line 1687, in main
>     illegalvars[0])
> RuntimeError: Variable 'rsut' is duplicated, and is a function of lat or lon: files rsut_Amon_NorESM2-LM_abrupt-4xCO2_r1i1p1f1_gn_004101-005012.nc, rsut_Amon_abrupt-4xCO2_NorESM2-LM_r1i1p1f1_gn_004101-005012.nc

@durack1 - do you have thoughts on Mark's suggested solution? 

This could be accomplished by passing in additional information into [xmlWrite](https://github.com/pochedls/xagg/blob/master/fx.py#L684). [At the point](https://github.com/pochedls/xagg/blob/master/fx.py#L921) where this function is called we have everything needed to scan as @mzelinka suggests (`filename = '+var+'Amon'+model+''+exp+''+ripf+'gn*.nc'`). 

A downside is that there may be misnamed files that have otherwise good data. Scanning only correctly named files would mean we can't access this data. 

Alternatively, @painter1 - could the misnamed files be removed from the directory in question? I think this is a one-off problem.

**Comment by durack1** [comment]
@pochedls I had started to go down the path of using lookup lists to figure out which directory paths match certain pieces (so test `activity_id` in the path position expected for e.g.) and then irrespective of the **wrong** path, the xml would be written with the correct entries as each filename element was tested, validated and then used in the filename, but, I didn't get to this

**Comment by pochedls** [comment]
> @pochedls I had started to go down the path of using lookup lists to figure out which directory paths match certain pieces (so test `activity_id` in the path position expected for e.g.) and then irrespective of the **wrong** path, the xml would be written with the correct entries as each filename element was tested, validated and then used in the filename, but, I didn't get to this

Does this mean you're in favor of this kind of feature? I forecast more problems than advantages.

**Comment by durack1** [comment]
@pochedls so it makes the most of the data that we have locally, BUT, it means we are indexing erroneous data that could be removed. To be honest I like the idea, BUT would also increment one of your flags
`CMIP5.CMIP.historical.LASG-CESS.FGOALS-g2.r4i1p1.mon.so.ocean.glb-z1-gu.v1.***0000000***.0.xml`
To indicate there was some kind of problem with the file
