### ISSUE TITLE
Missing ocean fixed fields (CNRM-CM6-1 piControl e.g.)

### ISSUE THREAD

**Issue by durack1** [pochedls/xagg#33]
In data travelings, a wrinkle with fixed fields has been uncovered.

Data that is locally available:
```
-bash-4.2$ ls -al ~/css03/esgf_publish/CMIP6/CMIP/CNRM-CERFACS/CNRM-CM6-1/
piControl/r1i1p1f2/Ofx/areacello/gn/v20180814/
total 8448
drwxrwsr-x 2 1682 climatew    4096 Aug 31  2018 .
drwxrwsr-x 3 1682 climatew    4096 Aug 22  2018 ..
-rw-rwSr-- 1 1682 climatew 8620506 Aug 14  2018 areacello_Ofx_CNRM-CM6-1_piControl_r1i1p1f2_gn.nc
```
Is not indexed by the xmls:
```
-bash-4.2$ ls ~/xclim/CMIP6/fx/areacello/*CNRM-CM6-1*
ls: cannot access ~/xclim/CMIP6/fx/areacello/*CNRM-CM6-1*: No such file or directory
```

I note there is some unusual permissions `-rw-rwSr--` on this file and directory, but I can `ncdump` the file, so wondering what is going wrong?

There is a parallel issue with deptho data that is available (e.g. [GFDL-ESM4.historical.r1i1p1f1.Ofx.deptho](https://esgf-node.llnl.gov/search/cmip6/?mip_era=CMIP6&activity_id=CMIP&institution_id=NOAA-GFDL&source_id=GFDL-ESM4&variable_id=deptho)) but this will need to be resolved elsewhere.

Ping @durack1 @pochedls @painter1 @jetesdal @gleckler1

**Comment by pochedls** [comment]
@durack1 - I see a "No write" error in the xagg database and I get an error when I try to create one for the path you list above. I'm not sure what we can do as this is probably a cdscan issue. You could try to reproduce my error (`AttributeError: 'dict_keys' object has no attribute 'append'`), see if an issue is logged, and, if not, create one (not sure if this is useful anymore).

**Comment by durack1** [comment]
@pochedls I hit a similar issue (I think):
```
(cdat821nompi) bash-4.2$ cdscan -x tmp.xml ~/css03/esgf_publish/CMIP6/CMIP/CNRM-CERFACS/CNRM-CM6-1/piControl/r1i1p1f2/Ofx/areacello/gn/v20180814/areacello_Ofx_CNRM-CM6-1_piControl_r1i1p1f2_gn.nc 
Finding common directory ...
Common directory: ~/css03/esgf_publish/CMIP6/CMIP/CNRM-CERFACS/CNRM-CM6-1/piControl/r1i1p1f2/Ofx/areacello/gn/v20180814/
Scanning files ...
~/css03/esgf_publish/CMIP6/CMIP/CNRM-CERFACS/CNRM-CM6-1/piControl/r1i1p1f2/Ofx/areacello/gn/v20180814/areacello_Ofx_CNRM-CM6-1_piControl_r1i1p1f2_gn.nc
Setting reference time units to 
Traceback (most recent call last):
  File "~anaconda3/envs/cdat821nompi/bin/cdscan", line 1842, in <module>
    main(sys.argv)
  File "~anaconda3/envs/cdat821nompi/bin/cdscan", line 1284, in main
    timeIsLinear = (referenceTime[0].lower().split() in
IndexError: string index out of range
```

**Comment by durack1** [comment]
Trying to hit things with a hammer (overwriting time dimension), doesn't work either:
```
(cdat821nompi) bash-4.2$ cdscan -x tmp.xml --time-linear '0,1,months since 1980,noleap' ~/css03/esgf_publish/CMIP6/CMIP/CNRM-CERFACS/CNRM-CM6-1/piControl/r1i1p1f2/Ofx/areacello/gn/v20180814/areacello_Ofx_CNRM-CM6-1_piControl_r1i1p1f2_gn.nc 
Finding common directory ...
Common directory: ~/css03/esgf_publish/CMIP6/CMIP/CNRM-CERFACS/CNRM-CM6-1/piControl/r1i1p1f2/Ofx/areacello/gn/v20180814/
Scanning files ...
~/css03/esgf_publish/CMIP6/CMIP/CNRM-CERFACS/CNRM-CM6-1/piControl/r1i1p1f2/Ofx/areacello/gn/v20180814/areacello_Ofx_CNRM-CM6-1_piControl_r1i1p1f2_gn.nc
Setting reference time units to 
Traceback (most recent call last):
  File "~anaconda3/envs/cdat821nompi/bin/cdscan", line 1842, in <module>
    main(sys.argv)
  File "~anaconda3/envs/cdat821nompi/bin/cdscan", line 1308, in main
    vartime[0],
  File "~anaconda3/envs/cdat821nompi/lib/python3.7/site-packages/cdms2/axis.py", line 2212, in __getitem__
    raise IndexError('index out of bounds')
IndexError: index out of bounds
```

**Comment by durack1** [comment]
This is a data issue, with a time dimension noted, but never defined:
```
(cdat821nompi) bash-4.2$ ncdump -ct ~/css03/esgf_publish/CMIP6/CMIP/CNRM-CERFACS/CNRM-CM6-1/piControl/r1i1p1f2/Ofx/areacello/gn/v20180814/areacello_Ofx_CNRM-CM6-1_piControl_r1i1p1f2_gn.nc
netcdf areacello_Ofx_CNRM-CM6-1_piControl_r1i1p1f2_gn {
dimensions:
	axis_nbounds = 2 ;
	x = 362 ;
	y = 294 ;
	nvertex = 4 ;
	time = UNLIMITED ; // (0 currently)
variables:
	double lat(y, x) ;
		lat:standard_name = "latitude" ;
		lat:long_name = "Latitude" ;
		lat:units = "degrees_north" ;
		lat:bounds = "bounds_lat" ;
	double lon(y, x) ;
		lon:standard_name = "longitude" ;
		lon:long_name = "Longitude" ;
		lon:units = "degrees_east" ;
		lon:bounds = "bounds_lon" ;
	double bounds_lon(y, x, nvertex) ;
	double bounds_lat(y, x, nvertex) ;
	float areacello(y, x) ;
		areacello:standard_name = "cell_area" ;
		areacello:long_name = "Grid-Cell Area" ;
		areacello:units = "m2" ;
		areacello:online_operation = "once" ;
		areacello:cell_methods = "area: sum" ;
		areacello:_FillValue = 1.e+20f ;
		areacello:missing_value = 1.e+20f ;
		areacello:coordinates = "lat lon" ;
		areacello:description = "Cell areas for any grid used to report ocean variables and variables which are requested as used on the model ocean grid (e.g. hfsso, which is a downward heat flux from the atmosphere interpolated onto the ocean grid). These cell areas should be defined to enable exact calculation of global integrals (e.g., of vertical fluxes of energy at the surface and top of the atmosphere)." ;
		areacello:history = "none" ;

// global attributes:
***
```
Whereas, for a valid Ofx/areacello dataset, no time dimension is defined
```
(cdat821nompi) bash-4.2$ ncdump -ct ~/css03/esgf_publish/CMIP6/CMIP/CSIRO-ARCCSS/ACCESS-CM2/1pctCO2/r1i1p1f1/Ofx/areacello/gn/v20191109/areacello_Ofx_ACCESS-CM2_1pctCO2_r1i1p1f1_gn.nc 
netcdf areacello_Ofx_ACCESS-CM2_1pctCO2_r1i1p1f1_gn {
dimensions:
	j = 300 ;
	i = 360 ;
	bnds = 2 ;
	vertices = 4 ;
variables:
	int j(j) ;
		j:units = "1" ;
		j:long_name = "cell index along second dimension" ;
	int i(i) ;
		i:units = "1" ;
		i:long_name = "cell index along first dimension" ;
	double latitude(j, i) ;
		latitude:standard_name = "latitude" ;
		latitude:long_name = "latitude" ;
		latitude:units = "degrees_north" ;
		latitude:missing_value = 1.e+20 ;
		latitude:_FillValue = 1.e+20 ;
		latitude:bounds = "vertices_latitude" ;
	double longitude(j, i) ;
		longitude:standard_name = "longitude" ;
		longitude:long_name = "longitude" ;
		longitude:units = "degrees_east" ;
		longitude:missing_value = 1.e+20 ;
		longitude:_FillValue = 1.e+20 ;
		longitude:bounds = "vertices_longitude" ;
	double vertices_latitude(j, i, vertices) ;
		vertices_latitude:units = "degrees_north" ;
		vertices_latitude:missing_value = 1.e+20 ;
		vertices_latitude:_FillValue = 1.e+20 ;
	double vertices_longitude(j, i, vertices) ;
		vertices_longitude:units = "degrees_east" ;
		vertices_longitude:missing_value = 1.e+20 ;
		vertices_longitude:_FillValue = 1.e+20 ;
	float areacello(j, i) ;
		areacello:standard_name = "cell_area" ;
		areacello:long_name = "Grid-Cell Area for Ocean Variables" ;
		areacello:comment = "Horizontal area of ocean grid cells" ;
		areacello:units = "m2" ;
		areacello:cell_methods = "area: sum" ;
		areacello:missing_value = 1.e+20f ;
		areacello:_FillValue = 1.e+20f ;
		areacello:coordinates = "latitude longitude" ;

// global attributes:
***
```

**Comment by durack1** [comment]
@pochedls it's not a xagg issue, so have labeled this invalid and will close
